
package com.hy.config.ums;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsPortType", targetNamespace = "http://ws.flaginfo.com.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsPortType {


    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in10
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Sms")
    @WebResult(name = "out", targetNamespace = "http://ws.flaginfo.com.cn")
    @RequestWrapper(localName = "Sms", targetNamespace = "http://ws.flaginfo.com.cn", className = "com.test.service.Sms")
    @ResponseWrapper(localName = "SmsResponse", targetNamespace = "http://ws.flaginfo.com.cn", className = "com.test.service.SmsResponse")
    public String sms(
            @WebParam(name = "in0", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in5,
            @WebParam(name = "in6", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in6,
            @WebParam(name = "in7", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in7,
            @WebParam(name = "in8", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in8,
            @WebParam(name = "in9", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in9,
            @WebParam(name = "in10", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in10);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Report")
    @WebResult(name = "out", targetNamespace = "http://ws.flaginfo.com.cn")
    @RequestWrapper(localName = "Report", targetNamespace = "http://ws.flaginfo.com.cn", className = "com.test.service.Report")
    @ResponseWrapper(localName = "ReportResponse", targetNamespace = "http://ws.flaginfo.com.cn", className = "com.test.service.ReportResponse")
    public String report(
            @WebParam(name = "in0", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://ws.flaginfo.com.cn")
                    String in2);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.test.service.ReplyResponse
     */
    @WebMethod(operationName = "Reply")
    @WebResult(name = "ReplyResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReplyResponse reply(
            @WebParam(name = "ReplyRequest", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
                    ReplyRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.test.service.ReplyConfirmResponse
     */
    @WebMethod(operationName = "ReplyConfirm")
    @WebResult(name = "ReplyConfirmResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReplyConfirmResponse replyConfirm(
            @WebParam(name = "ReplyConfirmRequest", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
                    ReplyConfirmRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.test.service.SearchSmsNumResponse
     */
    @WebMethod(operationName = "SearchSmsNum")
    @WebResult(name = "SearchSmsNumResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SearchSmsNumResponse searchSmsNum(
            @WebParam(name = "SearchSmsNumRequest", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
                    SearchSmsNumRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.test.service.AuditingResponse
     */
    @WebMethod(operationName = "Auditing")
    @WebResult(name = "AuditingResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AuditingResponse auditing(
            @WebParam(name = "AuditingRequest", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
                    AuditingRequest parameters);

}
